### ISSUE TITLE
Colab demo problem: AttributeError: module 'wandb.sdk' has no attribute 'lib'

### ISSUE THREAD

**Issue by FirestName** [SJTMusicTeam/Muskits#115] opened 2022-06-03 11:46 UTC
Upon running the "# Initialize singing generator" cell, first it seems that 
"!pip install sentry_sdk shortuuid pathtools"
has to be added.
Yet afterwards I'm not capable of solving the following:

AttributeError                            Traceback (most recent call last)
[<ipython-input-7-5c021bb20cef>](https://localhost:8080/#) in <module>()
      2 # Initialize singing generator
      3 get_ipython().system('pip install sentry_sdk shortuuid pathtools')
----> 4 from muskit.bin.svs_inference import SingingGenerate
      5 
      6 sing_generation = SingingGenerate(

3 frames
[/usr/local/lib/python3.7/dist-packages/wandb-0.13.0rc2-py3.7.egg/wandb/__init__.py](https://localhost:8080/#) in <module>()
     28 import wandb
     29 
---> 30 wandb.wandb_lib = wandb_sdk.lib
     31 
     32 init = wandb_sdk.init

AttributeError: module 'wandb.sdk' has no attribute 'lib'

what's up with this?

**Comment by ftshijt** [comment] 2022-06-03 18:13
Seems to be the issue from wandb itself, you can see that the error was thrown out when doing the import. Will have a check. Thanks for reporting

**Comment by ftshijt** [comment] 2022-06-03 19:38
I did not find a very good solution yet. But for a temporary fix: you can remove the import wandb in https://github.com/SJTMusicTeam/Muskits/blob/main/muskit/tasks/abs_task.py and https://github.com/SJTMusicTeam/Muskits/blob/main/muskit/train/reporter.py

**Comment by ftshijt** [comment] 2022-08-19 22:27
The issue is fixed by https://github.com/SJTMusicTeam/Muskits/pull/125

**Closed by ftshijt** 2022-08-19 22:27 UTC
